# Generated by Django 4.1.7 on 2023-02-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceraApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='peliculas',
            new_name='obras',
        ),
    ]
